#define Comment
all : strMain
VPATH = ../inc
dependents:/home/jitendriya/TestPrograms/StringHandling/src/obj
LIB := -lStringHandler
strMain:
	gcc -o strMain strMain.c -L/home/jitendriya/TestPrograms/StringHandling/src/obj -lStringHandler
clean:
	-rm -f strMain
